server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/note_db
    username: note_hub
    password: note_24
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    show-sql: true





